version: '3.8'

services:
  genshin_db:
    image: mysql:8
    container_name: stickdev_genshin_mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'genshin'
      MYSQL_PASSWORD: 'cM571cK'
      MYSQL_ROOT_PASSWORD: '5UP3r4DM1NP455W0rD'
    ports:
      - "3306:3306"
    volumes:
      - "../.docker-data/stickdev_genshin_mysql:/var/lib/mysql"
  genshin_php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: stickdev_genshin_php
    ports:
      - "9001:9001"
    volumes:
      - ".:/product/genshin/www:rw"
    networks:
      - genshin

  genshin_nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: stickdev_genshin_nginx
    ports:
      - "8080:80"
    volumes:
      - ".:/product/genshin/www:rw"
    networks:
      - genshin

networks:
  genshin:
    name: genshin
